# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-02 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='调查问卷名称')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='问卷创建日期')),
            ],
        ),
        migrations.CreateModel(
            name='SurveryChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=256, verbose_name='答案内容')),
                ('points', models.IntegerField(verbose_name='分值')),
            ],
        ),
        migrations.CreateModel(
            name='SurveryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='此处填写需要调查的问题...', max_length=255, verbose_name='调查问题')),
                ('date', models.DateField(auto_now_add=True)),
                ('answer_type', models.CharField(choices=[('single', '单选'), ('score', '打分'), ('suggestion', '建议')], default='score', max_length=32, verbose_name='问题类型')),
            ],
        ),
        migrations.CreateModel(
            name='SurveryRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='评分')),
                ('suggestion', models.TextField(blank=True, max_length=1024, null=True, verbose_name='建议')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='答题日期')),
                ('single', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='APP01.SurveryChoices', verbose_name='单选')),
                ('survery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.Survery', verbose_name='问卷')),
                ('survery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.SurveryItem', verbose_name='调查项')),
            ],
        ),
        migrations.AddField(
            model_name='surverychoices',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='APP01.SurveryItem', verbose_name='问题'),
        ),
    ]
